#include "ugly.h"

void Ugly::Uglify() {
	printf("LA STATUA\n");
	printf("Don Giovanni, a cenar teco\n");
	printf("M'invitasti e son venuto!\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("Non l'avrei giammai creduto;\n");
	printf("Ma farò quel che potrò.\n");
	printf("Leporello, un altra cena\n");
	printf("Fa che subito si porti!\n");
	printf("\n");
	printf("LEPORELLO\n");
	printf("facendo capolino di sotto alla tavola\n");
	printf("Ah padron! Siam tutti morti.\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("tirandolo fuori\n");
	printf("Vanne dico!\n");
	printf("\n");
	printf("LA STATUA\n");
	printf("a Leporello che è in atto di parlare\n");
	printf("Ferma un po'!\n");
	printf("Non si pasce di cibo mortale\n");
	printf("chi si pasce di cibo celeste;\n");
	printf("Altra cure più gravi di queste,\n");
	printf("Altra brama quaggiù mi guidò!\n");
	printf("\n");
	printf("LEPORELLO\n");
	printf("(La terzana d'avere mi sembra\n");
	printf("E le membra fermar più non so.)\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("Parla dunque! Che chiedi! Che vuoi?\n");
	printf("\n");
	printf("LA STATUA\n");
	printf("Parlo; ascolta! Più tempo non ho!\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("Parla, parla, ascoltando ti sto.\n");
	printf("\n");
	printf("LA STATUA\n");
	printf("Tu m'invitasti a cena,\n");
	printf("Il tuo dover or sai.\n");
	printf("Rispondimi: verrai\n");
	printf("tu a cenar meco?\n");
	printf("\n");
	printf("LEPORELLO\n");
	printf("da lontano, sempre tremando\n");
	printf("Oibò;\n");
	printf("tempo non ha, scusate.\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("A torto di viltate\n");
	printf("Tacciato mai sarò.\n");
	printf("\n");
	printf("LA STATUA\n");
	printf("Risolvi!\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("Ho già risolto!\n");
	printf("\n");
	printf("LA STATUA\n");
	printf("Verrai?\n");
	printf("\n");
	printf("LEPORELLO\n");
	printf("a Don Giovanni\n");
	printf("Dite di no!\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("Ho fermo il cuore in petto:\n");
	printf("Non ho timor: verrò!\n");
	printf("\n");
	printf("LA STATUA\n");
	printf("Dammi la mano in pegno!\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("porgendogli la mano\n");
	printf("Eccola! Ohimé!\n");
	printf("\n");
	printf("LA STATUA\n");
	printf("Cos'hai?\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("Che gelo è questo mai?\n");
	printf("\n");
	printf("LA STATUA\n");
	printf("Pentiti, cangia vita\n");
	printf("È l'ultimo momento!\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("vuol scoigliersi, ma invano\n");
	printf("No, no, ch'io non mi pento,\n");
	printf("Vanne lontan da me!\n");
	printf("\n");
	printf("LA STATUA\n");
	printf("Pentiti, scellerato!\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("No, vecchio infatuato!\n");
	printf("\n");
	printf("LA STATUA\n");
	printf("Pentiti!\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("No!\n");
	printf("\n");
	printf("LA STATUA\n");
	printf("Sì!\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("No!\n");
	printf("\n");
	printf("LA STATUA\n");
	printf("Ah! tempo più non v'è!\n");
	printf("\n");
	printf("Fuoco da diverse parti, il Commendatore sparisce, e s'apre una voragine.\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("Da qual tremore insolito\n");
	printf("Sento assalir gli spiriti!\n");
	printf("Dond'escono quei vortici\n");
	printf("Di foco pien d'orror?\n");
	printf("\n");
	printf("CORO DI DIAVOLI\n");
	printf("di sotterra, con voci cupe\n");
	printf("Tutto a tue colpe è poco!\n");
	printf("Vieni, c'è un mal peggior!\n");
	printf("\n");
	printf("DON GIOVANNI\n");
	printf("Chi l'anima mi lacera?\n");
	printf("Chi m'agita le viscere?\n");
	printf("Che strazio, ohimé, che smania!\n");
	printf("Che inferno, che terror!\n");
	printf("\n");
	printf("LEPORELLO\n");
	printf("(Che ceffo disperato!\n");
	printf("Che gesti da dannato!\n");
	printf("Che gridi, che lamenti!\n");
	printf("Come mi fa terror!)\n");
	printf("\n");
	printf("Cresce il fuoco, compariscono diverse furie, s'impossessano di Don Giovanni e seco lui sprofondano.\n");
}
