// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutoAdjust.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Down.h"
#include "Commands/Stop.h"
#include "Commands/Up.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	joystick1 = new Joystick(1);
	
	joystickButton3 = new JoystickButton(joystick1, 1);
	joystickButton3->WhileHeld(new AutoAdjust());
	joystickButton2 = new JoystickButton(joystick1, 1);
	joystickButton2->WhileHeld(new Down());
	joystickButton1 = new JoystickButton(joystick1, 1);
	joystickButton1->WhileHeld(new Up());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Stop", new Stop());

	SmartDashboard::PutData("Up", new Up());

	SmartDashboard::PutData("Down", new Down());

	SmartDashboard::PutData("AutoAdjust", new AutoAdjust());

	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getJoystick1() {
	return joystick1;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
