// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/drive1.h"
#include "Commands/drive2.h"
#include "Commands/drive3.h"
#include "Commands/square.h"
#include "Commands/stop.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	joy2 = new Joystick(2);
	
	joy2btn2 = new JoystickButton(joy2, 2);
	joy2btn2->WhenPressed(new stop());
	joy2btn1 = new JoystickButton(joy2, 1);
	joy2btn1->WhenPressed(new drive3());
	joy1 = new Joystick(1);
	
	btn3 = new JoystickButton(joy1, 3);
	btn3->WhileHeld(new square());
	btn2 = new JoystickButton(joy1, 2);
	btn2->WhenPressed(new drive2());
	btn1 = new JoystickButton(joy1, 1);
	btn1->WhenPressed(new drive1());
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
	SmartDashboard::PutData("drive1", new drive1());
	SmartDashboard::PutData("drive2", new drive2());
	SmartDashboard::PutData("drive3", new drive3());
	SmartDashboard::PutData("stop", new stop());
	SmartDashboard::PutData("square", new square());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getjoy2() {
	return joy2;
}
Joystick* OI::getjoy1() {
	return joy1;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
