// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "Command1.h"
#include "../OI.h"
#include "WPILib.h"
#include "SmartDashboard/SmartDashboard.h"
#include "../Commands/AutonomousCommand.h"
#include "../Commands/Command1.h"

Command1::Command1() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::subsystem1);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void Command1::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void Command1::Execute() {
	//Robot::oi->getJoystick1().GetY();
	if(Robot::oi->getJoystick1()->GetX() > .3 || Robot::oi->getJoystick1()->GetX() <-.3){
	Robot::subsystem1->setVal(Robot::oi->getJoystick1()->GetX());
	}
	else{
		Robot::subsystem1->setVal(0.0f);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool Command1::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void Command1::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Command1::Interrupted() {
	Robot::subsystem1->setVal(0.0f);
}
