// joyjoy paraphernalia
// if you think i'm going to comment all of this, you're a madman


#ifndef UGLY_H
#define UGLY_H
#define S1TRIG joy1.GetTrigger()
#define S1B2 joy1.GetRawButton(2)
#define S1B3 joy1.GetRawButton(3)
#define S1B4 joy1.GetRawButton(4)
#define S1B5 joy1.GetRawButton(5)
#define S1B6 joy1.GetRawButton(6)
#define S1B7 joy1.GetRawButton(7)
#define S1B8 joy1.GetRawButton(8)
#define S1B9 joy1.GetRawButton(9)
#define S1B10 joy1.GetRawButton(10)
#define S1B11 joy1.GetRawButton(11)
#define S1X joy1.GetX()
#define S1Y joy1.GetY()
#define S1Z joy1.GetThrottle()

#define S2TRIG joy2.GetTrigger()
#define S2B2 joy2.GetRawButton(2)
#define S2B3 joy2.GetRawButton(3)
#define S2B4 joy2.GetRawButton(4)
#define S2B5 joy2.GetRawButton(5)
#define S2B6 joy2.GetRawButton(6)
#define S2B7 joy2.GetRawButton(7)
#define S2B8 joy2.GetRawButton(8)
#define S2B9 joy2.GetRawButton(9)
#define S2B10 joy2.GetRawButton(10)
#define S2B11 joy2.GetRawButton(11)
#define S2X joy2.GetX()
#define S2Y joy2.GetY()
#define S2Z joy2.GetThrottle()

#define S3TRIG gamepad.GetTrigger()
#define S3B2 gamepad.GetRawButton(2)
#define S3B3 gamepad.GetRawButton(3)
#define S3B4 gamepad.GetRawButton(4)
#define S3B5 gamepad.GetRawButton(5)
#define S3B6 gamepad.GetRawButton(6)
#define S3B7 gamepad.GetRawButton(7)
#define S3B8 gamepad.GetRawButton(8)
#define S3B9 gamepad.GetRawButton(9)
#define S3B10 gamepad.GetRawButton(10)
#define S3B11 gamepad.GetRawButton(11)
#define S3X gamepad.GetX()
#define S3Y gamepad.GetY()
#define S3Z gamepad.GetThrottle()
#endif
