// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Command1.h"
#include "WPILib.h"
#include "Token.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	joystick1 = new Joystick(1);

	joystickButton1 = new JoystickButton(joystick1, 1);
	joystickButton1->WhileHeld(new AutonomousCommand());
	const char* token[1000][20];
//	try {
//		//Token tk;
//		//tk.parse("data.txt",token);
//	}
//	catch(...) {
//		printf("Tokenization has failed.");
//	}
	try {
		NetworkTable::SetServerMode();

		server = NetworkTable::GetTable("SmartDashboard");

		printf("%f\n", server->GetNumber("IMAGE_COUNT",0.0));
	}
	catch(...)
	{
		printf("\n\nNetworkTables has failed\n\n");
	}

	// SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("Command 1", new Command1());

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getJoystick1() {
	return joystick1;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
