// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::elevationSpd1 = NULL;
Encoder* RobotMap::elevationqenc = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	elevationSpd1 = new Talon(1, 1);
	lw->AddActuator("Elevation", "Spd1", (Talon*) elevationSpd1);
	
	elevationqenc = new Encoder(1, 1, 1, 2, false, Encoder::k4X);
	lw->AddSensor("Elevation", "qenc", elevationqenc);
	elevationqenc->SetDistancePerPulse(1.0);
        elevationqenc->SetPIDSourceParameter(Encoder::kRate);
        elevationqenc->Start();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
